development:
  adapter: postgresql
  encoding: unicode
  database: choice_dev5
  pool: 5
  username: hoverbird
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: choice_test
  pool: 5
  username: hoverbird
  password:

production:
  adapter: postgresql
  encoding: unicode
